Make necessary package imports

In [3]:
# imports 
import pandas as pd  
import numpy as np

Read data into scope

In [16]:
# use for displaying the data 
# read in the data
data_file = "../processed_data/all_data.csv"

comp_data = pd.read_csv(data_file)

Display data

In [14]:
comp_data.head()

,LastName,FirstName,Gender,Country,Date,Competition,Round,Location,Apparatus,Rank,D_Score,E_Score,Penalty,Score,Format Competition,Competitor
0,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",BB,76.0,4.8,6.766,NaN,11.566,July-2021 Olympic Games Japan,hadi abdul
1,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",FX,64.0,4.6,7.633,NaN,12.233,July-2021 Olympic Games Japan,hadi abdul
2,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",UE,74.0,5.1,6.500,NaN,11.600,July-2021 Olympic Games Japan,hadi abdul
3,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",VT,72.0,4.6,8.566,NaN,13.166,July-2021 Olympic Games Japan,hadi abdul
4,abdul hadi,farah ann,w,MAS,25 July 2021,Olympic Games,qual,"Tokyo, Japan",BB,76.0,4.8,6.766,NaN,11.566,July-2021 Olympic Games Japan,farah ann abdul hadi

In [18]:
# get a list of all of the unique features - especially for the olympic games - we want to make these all the same competition

competitors = list(comp_data["Competitor"].unique())
with open("competitors.csv", "w") as f:
    f.write("competitor\n")
    for i in competitors: 
        f.write("{}\n".format(i))

Competitor name fixes to make: 
1. hadi abdul -> farah ann abdul hadi
2.

In [22]:

def match_cost(x,y,c):
    if x==y: return 0
    else: return c

class sim_string:
    def __init__(self, x):
        self.x = x
        self.score = -1

    def __len__(self):
        return len(self.x)
    
    def compare_score(self, other, gc=1, mc=1, min_cost=1):
        '''
        run optimal string alignment for sim_string=self and sim_string=other
        '''
        OPT = dict()
        m = len(self)
        n = len(other)
    
        for i in range(m+1):
            OPT[(i,0)] = i*gc
        for j in range(n+1):
            OPT[(0,j)] = j*gc

        for i in range(1,m+1):
            for j in range(1,n+1):
                OPT[(i,j)] = min(match_cost(self.x[i-1],other.x[j-1],mc) + OPT[(i-1,j-1)],
                                 gc + OPT[(i-1,j)], 
                                 gc + OPT[(i,j-1)])
        self.score = OPT[(m,n)]
        print("{} v. {} = {}".format(self.x, other.x, self.score))

In [24]:
x = sim_string("alejandra alvarez diaz")
y = sim_string("alejandra sofia alvarez diaz")

x.compare_score(y, gc=0.3, mc=5, min_cost=10)

alejandra alvarez diaz v. alejandra sofia alvarez diaz = 1.8

In [13]:
# fix list

fixes = {("alice d amato", "alice d'amato"): "alice d'amato", 
         ("farah ann abdul hadi", "hadi abdul"): "farah ann abdul hadi", 
         ("elisa hämmerle", "elisa haemmerle"): "elisa hämmerle", 
         ("viktoriia listunova", "viktoria listunova"): "viktoria listunova", 
         ("vera pol", "vera van pol"): "vera van pol", 
         ("pauline schaefer betz", "pauline schaefer-betz"): "pauline schaefer-betz", 
         ("hua tien ting", "hua ting", "hua-tien ting"): "hua tien ting", 
         ("rakan alharith", "rakan al harithi", "rakah al harithi", "al harith rakan", "al-harith rakan"): "rakan al-harith", 
         ("alejandra alvarez diaz", "alejandra sofia alvarez diaz"): "alejandra alvarez diaz", 
         ("mc ewan ateer", "ewan mc ateer", "ewan mcateer"): "ewan mcateer", 
         ("mehmet ayberk", "mehmet ayberk kosak"): "mehmet ayberk", 
         ("gabriel barbosa", "gabriela barbosa"): "gabriela barbosa", 
         ("camil betances", "camil betances reyes"): "camil betances reyes",
         ("valentin brostella", "valentina brostella", "valentina abrostella arias"): "valentina brostella", 
         ("jossimar orlando calvo moreno", "jossimar orlando calvo moreno jo"): "jossimar orlando calvo moreno", 
         ("taylor christopulos", "taylor troy christopulos"): "taylor christopulos", 
         ("jorge rubio cerro", "jorge rubio"): "jorge rubio", 
         ("mc rhys clenaghan", "rhys mc clenaghan", "rhys mcclenaghan"): "rhys mcclenaghan", 
         ("matt cormier", "matthew cormier"): "matthew cormier", 
         ("agust davidsson", "agust ingi davidsson"): "agust davidsson", 
         ("melanie de jesus dos santos", "mélanie de jesus dos santos"): "mélanie de jesus dos santos", 
         ("alejandro de la cruz", "alejandro de la cruz gato"): "alejandro de la cruz", 
         ("fabian de luna", "fabian luna"): "fabian luna", 
         ("loran de munck", "loran munck"): "loran munck", 
         ("martijn de veer", "martijn veer"): "martijn veer", 
         ("laurie denommee", "laurie denommée"): "laurie denommee", 
         ("stella diaz", "stella loren diaz", "stella diaz muniz"): "stella diaz", 
         ("sam dick", "samual dick", "samuel dick"): "samuel dick", 
         ("dusan djordjevic", "dusan dordeivc"): "dusan dordevic", 
         ("ahmed elmaraghy", "ahmed el maraghy"): "ahmed el maraghy", 
         ("ruby evan", "ruby evans"): "ruby evans", 
         ("lea franceries", "léa franceries"): "lea franceries", 
         ("william fu allen", "william fu-allen", "william fuallen"): "william fu-allen", 
         ("luisa maia", "luisa gomes maia"): "luisa gomes maia", 
         ("jermain gruenberg", "jermain grünberg"): "jermain gruenberg", 
         ("hildur gudmundsdottir", "hildur maja gudmundsdottir"): "hildur gudmundsdottir", 
         ("yuri guimaraes", "yuri guimarães"): "yuri guimaraes", 
         ("yunus gundogdu", "yunus emre gundogdu", "yunus gündogdu"): "yunus gundogdu", 
         ("joseph hatoguan", "joseph judah hatoguan"): "joseph hatoguan", 
         ("hillary heron", "hillary heron soto"): "hillary heron", 
         ("ainhoa herrero lugo", "ainhoa sofia herrero lugo"): "ainhoa herrero lugo", 
         ("vinzenz hoeck", "vinzenz höck"): "vinzenz hoeck", 
         ("carlo hoerr", "carlo horr", "carlo hörr"): "carlo hoerr", 
         ("yen chang huang", "yen-chang  huang"): "yen chang huang", 
         ("yuan hsi hung", "yuan-hsi hung"): "yuan hsi hung", 
         ("karl idesjoe", "karl idesjö"): "karl idesjoe", 
         ("yo-seop  jeon", "yoseop jeon"): "yoseop jeon", 
         ("pavel karenejenko", "pavel karnejenko"): "pavel karnejenko", 
         ("mohamad khalil", "mohamed khalil"): "mohamed khalil", 
         ("anna lena koenig", "anna-lena könig"): "anna lena koenig", 
         ("shante koti", "shanté koti"): "shante koti", 
         ("severin kranzlmueller", "severin kranzlmüller"): "severin kranzmueller", 
         ("margret kristinsdottir", "margret lea kristinsdottir"): "margret kristinsdottir", 
         ("carina kroell", "carina kröll"): "carina kroell", 
         ("hansha gayashan kumarasinghege", "hansa gayashan kumarasinghege"): "hansha gayashan kumarasinghege", 
         ("kylee kvamme", "kylee ann kvamme"): "kylee kvamme", 
         ("pin lai", "pin ju lai", "pin-ju lai"): "pin ju lai", 
         ("xingyu lan", "xingyu  lan"): "xingyu lan", 
         ("thanh tung le", "thanh tùng  lê"): "thanh tung le", 
         ("cassandra lee", "cassandra paige lee"): "cassandra lee", 
         ("chih lee", "chih-kai lee", "chih kai lee"): "chih lee", 
         ("yi chun liao", "yi-chun liao"): "yi chun liao", 
         ("chaopan lin", "chaopan  lin"): "chaopan lin", 
         ("guan lin", "guan yi lin", "guan-yi lin"): "guan yi lin", 
         ("yi lin", "yi-chen lin", "yi chen lin"): "yi chen lin", 
         ("sara loikas", "sara sofia loikas"): "sara loikas", 
         ("jorge vega lopez", "jorge vega"): "jorge vega lopez", 
         ("noemie louon", "noémie louon"): "noemie louon", 
         ("julie madsoe", "julie madsø"): "julie madsoe", 
         ("sani maekelae", "sani mäkelä"): "sani maekelae", 
         ("razvan denis marc", "ravan-denis marc"): "razvan denis marc", 
         ("antonia marihuan", "antonia marihuan rubio"): "antonia marihuan rubio", 
         ("clay mason stephens", "clay masonstephens"): "clay mason stephens", 
         ("lorena medina", "lorena medina cobos"): "lorena medina", 
         ("dimitrijs mickevics", "dmitrijs mickevics"): "dimitrijs mickevics", 
         ("toma modoianu zseder", "toma modoianu-zseder"): "toma modoianu zseder", 
         ("alissa moerz", "alissa mörz"): "alissa moerz", 
         ("charlie moerz", "charlize mörz"): "charlie moerz", 
         ("sasiwimion mueangphuan", "sasiwimon mueangphuan"): "sasiwimon mueangphuan", 
         ("karla navas", "karla navas boyd"): "karla navas", 
         ("annalise newman achee", "annalise becca newman achee"): "annalise newman achee", 
         ("khanh phong nguyen", "van khanh phong nguyen"): "khanh phong nguyen", 
         ("audrys nin", "audrys nin reyes"): "audrys nin reyes", 
         ("isaac nunez", "isaac nuñez"): "isaac nunez", 
         ("aberdeen o driscoll", "aberdeen o'driscol"): "aberdeen o'driscol", 
         ("dagur olafsson", "dagur kari olafsson"): "dagur olafsson", 
         ("ahmet onder", "ahmet önder"): "ahmet onder", 
         ("ananya patanakul", "ananya belle patanakul"): "ananya patanakul", 
         ("dmitriy patanin", "dmitry patanin"): "dmitry patanin", 
         ("andres josue perez gines", "andres josue perez ginez"): "andres josue perez ginez", 
         ("makarena pinto adasme", "makarena daisy pinto adasme"): "makarena daisy pinto adasme", 
         ("jimi päivänen", "jimi pävänen"): "jimi pävänen", 
         ("lea quaas", "lea marie quaas"): "lea marie quaas", 
         ("larasati regganis", "larasati rengganis"): "larasati rengganis", 
         ("michael reid", "michael james reid"): "michael reid", 
         ("fred richard", "frederick richard"): "frederick richard", 
         ("keira rolston larking", "keira rolston-larking"): "keira rolston-larking", 
         ("leo saladino", "léo saladino"): "leo saladino", 
         ("göksu üctas sanli", "goksu uctas sanli"): "goksu uctas sanli", 
         ("karina schoenmaier", "karina schönmaier"): "karina schoenmaier", 
         ("yu shiao", "yu jan shiao", "yu-jan shiao"): "yu jan shiao", 
         ("poppy grace sticker", "poppy sticker"): "poppy sticker", 
         ("chia hung tang", "chia-hung tang"): "chia hung tang", 
         ("derin tanriyasukur", "derin tanriyasükür"): "derin tanriyasukur", 
         ("jonas thorisson", "jonas ingi thorisson"): "jonas thorisson", 
         ("jan gwynn timbang", "jann gwynn timbang"): "jan gwynn timbang", 
         ("juliane toessebro", "juliane tøssebro"): "juliane toessebro", 
         ("wei tseng", "wei sheng tseng", "wei-sheng tseng"): "wei sheng tseng", 
         ("kim vanstroem", "kim vanstrom", "kim wanström"): "kim vanstrom", 
         ("adria vera", "adria vera mora"): "adria vera", 
         ("daniel villafane", "daniel villafañe", "daniel angel villafane"): "daniel angel villafane", 
         ("max whitlock", "max whitlock obe"): "max whitlock", 
         ("hiu ying wong", "hiu ying angel wong"): "hiu ying wong", 
         ("sing wu", "sing fen wu"): "sing fen wu", 
         ("ruoteng xiao", "ruoteng  xiao"): "ruoteng xiao", 
         ("korkem yerbossynkyzy", "korkem yerobssynkyzy"): "korkem yerobssynkyzy", 
         ("jin-seong  yun", "jinseong yun"): "jinseong yun", 
         ("sam zakutney", "samuel zakutney"): "samuel zakutney", 
         ("boheng zhang", "boheng  zhang"): "boheng zhang", 
}
len(fixes)
# continue from line 142 in the "competitor_fixes.txt" file when fixing the names

119

In [20]:
dat = comp_data[comp_data["Competitor"] == "nicole diez"]
dat.head()

Empty DataFrame
Columns: [LastName, FirstName, Gender, Country, Date, Competition, Round, Location, Apparatus, Rank, D_Score, E_Score, Penalty, Score, Format Competition, Competitor]
Index: []

In [17]:
from features import fixes

for name_set in fixes: 
    for unique_name in list(comp_data["Competitor"].unique()):
        if unique_name in name_set: comp_data.loc[comp_data["Competitor"] == unique_name, "Competitor"] = fixes[name_set]

comp_data.head()

,LastName,FirstName,Gender,Country,Date,Competition,Round,Location,Apparatus,Rank,D_Score,E_Score,Penalty,Score,Format Competition,Competitor
0,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",BB,76.0,4.8,6.766,NaN,11.566,July-2021 Olympic Games Japan,farah ann abdul hadi
1,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",FX,64.0,4.6,7.633,NaN,12.233,July-2021 Olympic Games Japan,farah ann abdul hadi
2,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",UE,74.0,5.1,6.500,NaN,11.600,July-2021 Olympic Games Japan,farah ann abdul hadi
3,abdul,hadi,w,MAS,SUN 25 JUL 2021,Olympic Games,AAqual,"Tokyo, Japan",VT,72.0,4.6,8.566,NaN,13.166,July-2021 Olympic Games Japan,farah ann abdul hadi
4,abdul hadi,farah ann,w,MAS,25 July 2021,Olympic Games,qual,"Tokyo, Japan",BB,76.0,4.8,6.766,NaN,11.566,July-2021 Olympic Games Japan,farah ann abdul hadi

In [18]:
comp_data["Competitor"].nunique()

1822